# DNS server configuration for CN Project
port=53
listen-address=127.0.0.1,10.7.15.236
bind-interfaces

# Domain records for Team 1
address=/app.team1.test/10.7.17.151
address=/api.team1.test/10.7.17.151
